"""
Theme Database — 200+ categories for automatic video theme detection.
Used by video_intelligence.py fallback when Gemini is unavailable.
"""

# ═══ THEME DATABASE ═══
# Format: "theme_name": ["keyword1", "keyword2", ...]
# Organized by super-category for maintenance

THEME_DB = {
    # ── HISTORY ──
    "ancient egypt": ["pharaoh", "pyramid", "sphinx", "hieroglyph", "nile", "mummy", "tutankhamun", "cleopatra"],
    "ancient rome": ["roman", "gladiator", "colosseum", "caesar", "senate", "legion", "patrician", "republic"],
    "ancient greece": ["greek", "athens", "sparta", "olympus", "socrates", "plato", "acropolis", "democracy"],
    "medieval history": ["medieval", "knight", "castle", "crusade", "feudal", "plague", "king", "monastery"],
    "renaissance": ["renaissance", "michelangelo", "leonardo", "florence", "painting", "reformation"],
    "viking history": ["viking", "norse", "ragnar", "odin", "longship", "scandinavia", "valhalla"],
    "aztec maya": ["aztec", "maya", "inca", "tenochtitlan", "sacrifice", "mesoamerican", "quetzalcoatl"],
    "chinese history": ["dynasty", "emperor", "mandate", "confucius", "silk road", "great wall", "forbidden city"],
    "japanese history": ["samurai", "shogun", "bushido", "feudal japan", "katana", "ninja", "emperor meiji"],
    "ottoman empire": ["ottoman", "sultan", "constantinople", "janissary", "caliphate", "suleiman"],
    "colonial history": ["colonial", "colonization", "imperialism", "colony", "independence", "revolution"],
    "industrial revolution": ["industrial", "factory", "steam", "invention", "manufacturing", "coal", "railroad"],
    "cold war": ["cold war", "soviet", "nuclear", "berlin wall", "communism", "capitalism", "iron curtain"],
    "slavery history": ["slavery", "slave", "abolition", "plantation", "freedom", "emancipation", "underground"],
    "ancient mesopotamia": ["mesopotamia", "sumerian", "babylon", "cuneiform", "ziggurat", "tigris", "euphrates"],
    "prehistoric": ["prehistoric", "caveman", "stone age", "neolithic", "paleolithic", "mammoth", "fossil"],
    "french revolution": ["bastille", "guillotine", "napoleon", "bourbon", "revolution francaise", "jacobin"],
    "american civil war": ["confederate", "union", "gettysburg", "lincoln", "abolition", "secession"],
    "world history": ["empire", "ancient", "civilization", "conquest", "dynasty", "kingdom", "ruler"],
    # ── WARS & MILITARY ──
    "world war 1": ["wwi", "trench", "somme", "verdun", "armistice", "kaiser", "gallipoli", "doughboy"],
    "world war 2": ["wwii", "hitler", "nazi", "holocaust", "d-day", "normandy", "auschwitz", "blitz", "pearl harbor"],
    "vietnam war": ["vietnam", "saigon", "vietcong", "napalm", "helicopter", "guerrilla"],
    "korean war": ["korean war", "38th parallel", "inchon", "armistice", "dmz"],
    "war history": ["war", "battle", "soldier", "army", "conquest", "invasion", "troops", "military", "combat"],
    "special forces": ["special forces", "navy seal", "delta force", "commando", "sniper", "covert", "tactical"],
    "nuclear weapons": ["nuclear", "atomic", "hiroshima", "nagasaki", "missile", "warhead", "uranium", "bomb"],
    "terrorism": ["terrorist", "terrorism", "attack", "extremist", "radical", "bombing", "hostage"],
    # ── SCIENCE ──
    "space exploration": ["planet", "galaxy", "universe", "astronaut", "nasa", "cosmos", "orbit", "rocket"],
    "astronomy": ["telescope", "constellation", "nebula", "supernova", "pulsar", "quasar", "exoplanet"],
    "black holes": ["black hole", "event horizon", "singularity", "hawking", "gravitational", "spacetime"],
    "mars exploration": ["mars", "rover", "curiosity", "perseverance", "martian", "red planet", "colonize"],
    "physics": ["quantum", "relativity", "particle", "atom", "proton", "neutron", "higgs", "entropy"],
    "chemistry": ["chemical", "molecule", "element", "periodic", "reaction", "compound", "catalyst"],
    "biology": ["cell", "dna", "gene", "evolution", "species", "organism", "mutation", "protein"],
    "genetics": ["genetic", "chromosome", "genome", "hereditary", "crispr", "clone", "dna sequencing"],
    "microbiology": ["bacteria", "virus", "microbe", "pathogen", "microscope", "infection", "antibiotic"],
    "paleontology": ["dinosaur", "fossil", "jurassic", "tyrannosaurus", "extinction", "trilobite", "paleontolog"],
    "geology": ["tectonic", "magma", "mineral", "sediment", "geological", "stratum", "erosion", "crystal"],
    "neuroscience": ["neuron", "synapse", "cortex", "dopamine", "serotonin", "neuroplasticity", "amygdala"],
    "mathematics": ["equation", "theorem", "calculus", "geometry", "algebra", "prime", "infinity", "fractal"],
    # ── MEDICINE & HEALTH ──
    "health supplements": ["supplement", "vitamin", "omega", "capsule", "nutrient", "herb", "extract", "dosage"],
    "medical science": ["doctor", "hospital", "disease", "patient", "treatment", "medicine", "surgery", "diagnosis"],
    "nutrition": ["nutrition", "diet", "calorie", "protein", "carbohydrate", "metabolism", "fiber", "antioxidant"],
    "mental health": ["anxiety", "depression", "therapy", "counseling", "ptsd", "trauma", "bipolar", "schizophrenia"],
    "cancer research": ["cancer", "tumor", "chemotherapy", "oncology", "carcinogen", "remission", "malignant"],
    "pandemic disease": ["pandemic", "epidemic", "outbreak", "contagion", "quarantine", "vaccine", "covid", "plague"],
    "pharmaceutical": ["drug", "pharmaceutical", "fda", "clinical trial", "prescription", "side effect", "dosage"],
    "fitness exercise": ["workout", "exercise", "muscle", "training", "cardio", "gym", "bodybuilding", "strength"],
    "alternative medicine": ["acupuncture", "ayurveda", "homeopathy", "holistic", "herbal", "naturopathy"],
    "aging longevity": ["aging", "longevity", "telomere", "senescence", "lifespan", "anti-aging", "centenarian"],
    "dental health": ["teeth", "dental", "cavity", "orthodont", "gum", "molar", "enamel", "dentist"],
    "eye health": ["vision", "eye", "retina", "cataract", "glaucoma", "myopia", "cornea", "ophthalmolog"],
    "sleep science": ["sleep", "insomnia", "circadian", "melatonin", "rem", "narcolepsy", "apnea"],
    # ── TECHNOLOGY ──
    "technology": ["computer", "software", "robot", "digital", "internet", "algorithm", "silicon", "processor"],
    "artificial intelligence": ["ai", "artificial intelligence", "machine learning", "neural network", "chatgpt", "deepfake"],
    "cybersecurity": ["hacker", "cybersecurity", "encryption", "firewall", "malware", "phishing", "ransomware"],
    "robotics": ["robot", "automation", "humanoid", "servo", "actuator", "android", "mechanical"],
    "blockchain crypto": ["blockchain", "bitcoin", "ethereum", "cryptocurrency", "mining", "decentralized", "nft"],
    "electric vehicles": ["electric vehicle", "tesla", "battery", "charging", "ev", "autonomous", "self-driving"],
    "social media": ["social media", "instagram", "tiktok", "facebook", "twitter", "influencer", "viral", "algorithm"],
    "smartphones": ["smartphone", "iphone", "android", "mobile", "app", "touchscreen", "5g"],
    "virtual reality": ["virtual reality", "vr", "augmented", "metaverse", "headset", "immersive", "hologram"],
    "3d printing": ["3d printing", "additive", "filament", "prototype", "cad", "layer"],
    "quantum computing": ["quantum computer", "qubit", "superposition", "entanglement", "quantum supremacy"],
    "drones": ["drone", "uav", "quadcopter", "aerial", "fpv", "unmanned", "remote pilot"],
    # ── NATURE & ENVIRONMENT ──
    "nature wildlife": ["ocean", "forest", "animal", "ecosystem", "wildlife", "marine", "coral", "jungle"],
    "ocean deep sea": ["deep sea", "mariana", "submarine", "underwater", "abyss", "bioluminescent", "trench"],
    "rainforest": ["rainforest", "amazon", "tropical", "canopy", "deforestation", "biodiversity", "jungle"],
    "arctic antarctic": ["arctic", "antarctic", "polar", "glacier", "iceberg", "permafrost", "tundra", "penguin"],
    "volcanoes": ["volcano", "eruption", "lava", "magma", "crater", "vesuvius", "yellowstone", "caldera"],
    "earthquakes": ["earthquake", "seismic", "fault line", "richter", "tectonic", "tremor", "aftershock"],
    "hurricanes storms": ["hurricane", "cyclone", "typhoon", "storm", "tornado", "wind", "category"],
    "climate change": ["climate", "global warming", "greenhouse", "carbon", "ice cap", "sea level", "emissions"],
    "endangered species": ["endangered", "extinction", "poaching", "conservation", "habitat", "ivory", "rhino"],
    "insects": ["insect", "beetle", "butterfly", "ant", "bee", "mosquito", "spider", "entomolog"],
    "birds": ["bird", "eagle", "hawk", "parrot", "migration", "feather", "nest", "ornitholog"],
    "marine life": ["whale", "dolphin", "shark", "octopus", "jellyfish", "squid", "seahorse", "coral reef"],
    "plants botany": ["plant", "flower", "root", "photosynthesis", "seed", "pollen", "chlorophyll", "botany"],
    "desert": ["desert", "sahara", "sand dune", "oasis", "cactus", "arid", "drought", "camel"],
    "mountains": ["mountain", "everest", "himalaya", "alpine", "summit", "climbing", "altitude", "peak"],
    # ── CRIME & LAW ──
    "crime investigation": ["murder", "crime", "police", "detective", "serial", "criminal", "prison", "forensic"],
    "serial killers": ["serial killer", "psychopath", "victim", "homicide", "manhunt", "profiler"],
    "organized crime": ["mafia", "cartel", "gang", "trafficking", "smuggling", "godfather", "mob", "syndicate"],
    "cybercrime": ["cybercrime", "identity theft", "dark web", "fraud", "scam", "money laundering"],
    "prison system": ["prison", "inmate", "correctional", "parole", "solitary", "warden", "incarceration"],
    "court law": ["trial", "judge", "jury", "verdict", "prosecution", "defense", "testimony", "lawsuit"],
    "espionage": ["spy", "espionage", "intelligence", "cia", "mi6", "kgb", "undercover", "classified"],
    "cold cases": ["cold case", "unsolved", "missing person", "disappearance", "investigation", "evidence"],
    # ── FINANCE & ECONOMICS ──
    "finance economy": ["market", "economy", "stock", "investment", "bank", "inflation", "crypto", "recession"],
    "real estate": ["real estate", "property", "mortgage", "housing", "rent", "landlord", "construction"],
    "entrepreneurship": ["startup", "entrepreneur", "business", "founder", "venture", "innovation", "pitch"],
    "wall street": ["wall street", "trading", "hedge fund", "portfolio", "dow jones", "nasdaq", "derivatives"],
    "personal finance": ["savings", "budget", "debt", "credit", "retirement", "401k", "financial planning"],
    "billionaires": ["billionaire", "wealth", "fortune", "mogul", "tycoon", "richest", "net worth"],
    "economic crisis": ["crash", "depression", "recession", "bailout", "bankruptcy", "bubble", "collapse"],
    # ── PSYCHOLOGY & PHILOSOPHY ──
    "psychology": ["brain", "mind", "psychology", "behavior", "emotion", "mental", "cognitive", "subconscious"],
    "philosophy": ["philosophy", "existential", "morality", "ethics", "metaphysics", "stoicism", "nihilism"],
    "personality": ["introvert", "extrovert", "narcissist", "empathy", "personality", "trait", "temperament"],
    "dreams": ["dream", "lucid", "nightmare", "subconscious", "rem sleep", "interpretation", "surreal"],
    "manipulation": ["manipulation", "gaslighting", "propaganda", "brainwashing", "persuasion", "deception"],
    "addiction": ["addiction", "substance", "alcoholism", "withdrawal", "rehab", "relapse", "dependency"],
    # ── RELIGION & SPIRITUALITY ──
    "religion spirituality": ["god", "bible", "church", "religion", "faith", "spiritual", "prayer", "holy"],
    "christianity": ["jesus", "christ", "apostle", "gospel", "resurrection", "baptism", "catholic", "protestant"],
    "islam": ["allah", "muhammad", "quran", "mosque", "mecca", "ramadan", "halal", "islamic"],
    "buddhism": ["buddha", "meditation", "zen", "nirvana", "karma", "dharma", "enlightenment", "temple"],
    "hinduism": ["hindu", "vishnu", "shiva", "krishna", "reincarnation", "vedas", "mantra", "chakra"],
    "mythology": ["myth", "mytholog", "legend", "folklore", "demigod", "hero", "oracle", "titan"],
    "occult paranormal": ["paranormal", "ghost", "haunted", "supernatural", "witch", "occult", "demon", "exorcism"],
    "astrology": ["zodiac", "horoscope", "astrology", "mercury retrograde", "birth chart", "lunar"],
    # ── FOOD & COOKING ──
    "food cooking": ["food", "recipe", "cooking", "kitchen", "chef", "ingredient", "restaurant", "cuisine"],
    "baking": ["baking", "bread", "cake", "pastry", "dough", "flour", "oven", "dessert"],
    "wine beverages": ["wine", "vineyard", "grape", "sommelier", "whiskey", "brewery", "cocktail", "ferment"],
    "street food": ["street food", "vendor", "food truck", "market", "stall", "fried", "skewer"],
    "veganism": ["vegan", "plant-based", "vegetarian", "tofu", "cruelty-free", "organic", "sustainable food"],
    # ── SPORTS ──
    "sports athletics": ["football", "soccer", "olympic", "champion", "athlete", "game", "competition", "medal"],
    "basketball": ["basketball", "nba", "dunk", "court", "three-pointer", "playoffs", "mvp"],
    "football soccer": ["soccer", "football", "goal", "striker", "goalkeeper", "world cup", "premier league"],
    "american football": ["nfl", "quarterback", "touchdown", "super bowl", "gridiron", "tackle"],
    "combat sports": ["boxing", "mma", "ufc", "wrestling", "martial arts", "knockout", "champion belt"],
    "motorsport": ["formula 1", "f1", "nascar", "racing", "motorsport", "circuit", "lap", "pit stop"],
    "extreme sports": ["skydiving", "bungee", "surfing", "snowboard", "paragliding", "base jump", "extreme"],
    "swimming": ["swimming", "pool", "freestyle", "backstroke", "butterfly", "diving", "aquatic"],
    # ── POLITICS & SOCIETY ──
    "politics government": ["president", "government", "election", "political", "congress", "democracy", "senate"],
    "geopolitics": ["geopolitics", "nato", "sanctions", "diplomacy", "sovereignty", "territory", "alliance"],
    "human rights": ["human rights", "freedom", "oppression", "equality", "discrimination", "refugee", "asylum"],
    "immigration": ["immigration", "border", "migrant", "visa", "deportation", "citizenship", "refugee"],
    "feminism gender": ["feminism", "gender", "equality", "patriarchy", "suffrage", "reproductive", "empowerment"],
    "racism": ["racism", "segregation", "apartheid", "civil rights", "discrimination", "prejudice"],
    "censorship": ["censorship", "free speech", "propaganda", "banned", "surveillance", "privacy"],
    # ── TRAVEL & GEOGRAPHY ──
    "travel geography": ["country", "travel", "island", "mountain", "coast", "expedition", "landscape", "tourism"],
    "ancient ruins": ["ruins", "archaeological", "excavation", "artifact", "temple", "tomb", "ancient site"],
    "underwater exploration": ["diving", "scuba", "shipwreck", "underwater", "reef", "submarine", "deep dive"],
    "urban exploration": ["urban", "abandoned", "skyscraper", "metropolis", "cityscape", "underground", "tunnel"],
    "survival wilderness": ["survival", "wilderness", "bushcraft", "shelter", "campfire", "foraging", "stranded"],
    "aviation": ["airplane", "aviation", "pilot", "airport", "flight", "aircraft", "cockpit", "turbulence"],
    "nautical maritime": ["ship", "vessel", "captain", "port", "harbor", "maritime", "naval", "anchor", "titanic"],
    # ── ART & CULTURE ──
    "art painting": ["painting", "artist", "gallery", "canvas", "portrait", "masterpiece", "impressionism"],
    "music industry": ["music", "musician", "concert", "album", "guitar", "lyrics", "band", "producer"],
    "cinema film": ["movie", "film", "director", "actor", "hollywood", "cinema", "screenplay", "oscar"],
    "literature": ["book", "novel", "author", "literature", "poetry", "fiction", "bestseller", "publish"],
    "architecture": ["architecture", "building", "design", "skyscraper", "blueprint", "facade", "dome"],
    "fashion": ["fashion", "designer", "runway", "couture", "trend", "garment", "textile", "model"],
    "photography": ["photography", "camera", "lens", "exposure", "portrait", "shutter", "composition"],
    "dance": ["dance", "ballet", "choreography", "hip hop", "salsa", "tango", "contemporary", "breakdance"],
    "theater": ["theater", "stage", "drama", "broadway", "shakespeare", "performance", "acting", "monologue"],
    # ── CONSTRUCTION & ENGINEERING ──
    "construction engineering": ["building", "construction", "bridge", "engineer", "architecture", "steel", "crane"],
    "mega structures": ["megastructure", "dam", "tunnel", "skyscraper", "infrastructure", "canal", "pipeline"],
    "mining": ["mining", "coal", "gold", "diamond", "ore", "quarry", "excavation", "drilling"],
    "oil energy": ["oil", "petroleum", "refinery", "drilling", "pipeline", "opec", "barrel", "crude"],
    "renewable energy": ["solar", "wind turbine", "renewable", "hydroelectric", "geothermal", "biomass"],
    "nuclear energy": ["nuclear reactor", "fission", "fusion", "chernobyl", "fukushima", "radioactive"],
    # ── TRANSPORTATION ──
    "cars automotive": ["car", "automobile", "engine", "horsepower", "transmission", "supercar", "vintage car"],
    "trains railways": ["train", "railway", "locomotive", "station", "bullet train", "freight", "subway"],
    "ships maritime": ["ship", "cargo", "container", "cruise", "tanker", "port", "dock", "fleet"],
    "aircraft": ["aircraft", "jet", "boeing", "airbus", "supersonic", "stealth", "fighter jet"],
    "space travel": ["spacecraft", "rocket", "launch", "satellite", "space station", "astronaut", "orbit"],
    # ── CONSPIRACY & MYSTERIES ──
    "conspiracy theories": ["conspiracy", "secret", "illuminati", "hidden", "cover-up", "deep state", "classified"],
    "ufo aliens": ["ufo", "alien", "extraterrestrial", "roswell", "abduction", "sighting", "area 51"],
    "lost civilizations": ["atlantis", "lost city", "ancient", "ruins", "undiscovered", "legend", "artifact"],
    "secret societies": ["freemason", "secret society", "knights templar", "skull and bones", "lodge"],
    "unexplained": ["bermuda triangle", "crop circle", "bigfoot", "loch ness", "yeti", "mothman"],
    # ── EDUCATION & SCIENCE ──
    "education": ["school", "university", "student", "professor", "degree", "curriculum", "scholarship"],
    "language": ["language", "linguistics", "grammar", "translation", "bilingual", "dialect", "etymology"],
    "history of science": ["discovery", "invention", "scientist", "laboratory", "experiment", "breakthrough"],
    # ── BIOGRAPHY ──
    "biography": ["born", "childhood", "career", "legacy", "famous", "genius", "pioneer", "visionary"],
    "royalty": ["queen", "king", "prince", "princess", "royal", "monarch", "throne", "crown", "palace"],
    "inventors": ["inventor", "patent", "innovation", "eureka", "prototype", "creation", "genius"],
    "dictators": ["dictator", "tyrant", "authoritarian", "regime", "oppression", "propaganda", "despot"],
    # ── NATURAL DISASTERS ──
    "natural disasters": ["earthquake", "volcano", "tsunami", "hurricane", "tornado", "disaster", "flood"],
    "wildfires": ["wildfire", "bushfire", "arson", "firefighter", "drought", "blaze", "evacuation"],
    "avalanche": ["avalanche", "landslide", "mudslide", "rockfall", "debris", "mountain rescue"],
    # ── SOCIAL ISSUES ──
    "poverty": ["poverty", "homeless", "hunger", "starvation", "inequality", "slum", "charity", "aid"],
    "education crisis": ["illiteracy", "dropout", "underfunded", "teacher shortage", "education gap"],
    "drug trade": ["drug", "cocaine", "heroin", "cartel", "trafficking", "overdose", "narcotics", "dea"],
    "child welfare": ["orphan", "adoption", "child labor", "abuse", "foster", "unicef", "protection"],
    # ── ANIMALS ──
    "dogs": ["dog", "puppy", "canine", "breed", "retriever", "shepherd", "husky", "training"],
    "cats": ["cat", "kitten", "feline", "persian", "siamese", "tabby", "whiskers"],
    "horses": ["horse", "equestrian", "stallion", "mare", "foal", "racing", "derby", "jockey"],
    "reptiles": ["reptile", "snake", "lizard", "crocodile", "turtle", "iguana", "venom", "scales"],
    "big cats": ["lion", "tiger", "leopard", "cheetah", "jaguar", "panther", "predator", "safari"],
    "primates": ["gorilla", "chimpanzee", "orangutan", "monkey", "primate", "ape", "baboon"],
    "aquarium fish": ["fish", "aquarium", "tropical fish", "goldfish", "saltwater", "freshwater", "tank"],
    # ── LIFESTYLE ──
    "parenting": ["parenting", "child", "baby", "mother", "father", "pregnancy", "toddler", "newborn"],
    "relationships": ["relationship", "love", "marriage", "divorce", "dating", "couple", "romance"],
    "self improvement": ["self improvement", "motivation", "productivity", "habit", "mindset", "discipline"],
    "minimalism": ["minimalism", "declutter", "simplify", "essentials", "less is more", "intentional"],
    "luxury lifestyle": ["luxury", "mansion", "yacht", "private jet", "penthouse", "exclusive", "premium"],
    "gardening": ["garden", "plant", "grow", "soil", "compost", "harvest", "greenhouse", "seed"],
    "diy crafts": ["diy", "craft", "handmade", "woodworking", "upcycle", "paint", "sewing", "knitting"],
    "gaming": ["gaming", "esports", "console", "playstation", "xbox", "streamer", "twitch", "gamer"],
    "tattoo": ["tattoo", "ink", "body art", "piercing", "tattoo artist", "needle"],
    "beauty cosmetics": ["makeup", "skincare", "cosmetic", "beauty", "concealer", "serum", "moisturizer"],
    "wedding": ["wedding", "bride", "groom", "ceremony", "reception", "engagement", "honeymoon"],
    "pets general": ["pet", "veterinarian", "shelter", "adoption", "collar", "leash", "grooming"],
    "home design": ["interior design", "furniture", "decor", "renovation", "remodel", "flooring", "wallpaper"],
}

# ═══ EMOTION TRIGGERS ═══
EMOTION_DB = {
    "dramatic": ["died", "death", "killed", "destroyed", "war", "battle", "catastroph", "tragic",
                  "massacre", "genocide", "slaughter", "annihilat", "devastat", "fatal", "perish"],
    "urgent": ["danger", "warning", "crisis", "emergency", "threat", "critical", "alert", "alarm",
               "imminent", "escalat", "panic", "evacuate", "collapse", "breaking"],
    "mysterious": ["mystery", "unknown", "secret", "hidden", "unexplained", "disappear", "enigma",
                   "puzzle", "cryptic", "anomaly", "strange", "bizarre", "eerie", "unsolved"],
    "hopeful": ["hope", "cure", "solution", "breakthrough", "discover", "future", "progress",
                "recovery", "triumph", "miracle", "inspiring", "overcome", "resilient"],
    "calm": ["peaceful", "calm", "nature", "beauty", "gentle", "tranquil", "serene", "harmony",
             "meditat", "relaxing", "soothing", "quiet", "stillness"],
    "epic": ["legendary", "monumental", "colossal", "magnificent", "extraordinary", "unprecedented",
             "historic", "greatest", "record-breaking", "iconic"],
    "dark": ["horror", "terror", "nightmare", "sinister", "evil", "corrupt", "cruel", "torture",
             "suffering", "agony", "gruesome", "macabre"],
    "nostalgic": ["remember", "memory", "childhood", "retro", "classic", "vintage", "old days",
                  "generation", "tradition", "heritage"],
    "angry": ["outrage", "injustice", "corruption", "scandal", "betray", "fraud", "exploit",
              "inequality", "abuse", "oppression"],
    "inspirational": ["achieve", "dream", "succeed", "passion", "dedicate", "persist", "courage",
                      "believe", "transform", "empower"],
}
